### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by GTO2013** [jonsole/toyotune#1]
Hi,
I just found this repository and I find it really interesting. I have an E36 with a 2JZ GTE VVTI engine from a JZS161 Aristo and I was always curious how these aftermarket daughterboards work. These ECUs respond pretty well to hardware changes, so if you could remap it for bigger injectors it would already be super useful. Do you have any further information on how to install the daughterboard and how to extract the current binary and program section?

I have done quite a bit of RomRaider development, maybe we can start a definition file for this or other Toyota ECUs? I could also integrate the checksum algorithm directly into RomRaider or add other custom code to make this work.

**Comment by jonsole** [comment]
Hi, sorry I've only just noticed your comment.  Unfortunately Toyota changed the ECU architecture when they added VVTI so none of this is directly applicable.  It's a shame as I have an JZS161 Aristo and I'd love to be able to tune it.

**Comment by GTO2013** [comment]
No Problem, do you think it would be possible to re-tune a TOMS or MINES ecu instead? So you "only" have to worry about the SW part and not the additional HW

**Comment by jonsole** [comment]
It might be possible to re-rune a TOMs or MINES ECU but there's a good chance the maps are encrypted.
Earlier modified ECUs for MR2 etc  had a simple 'encryption' which was easy to brute force decrypt using the standard ROM image as a reference.
